### ISSUE TITLE
Update Middleware to support Django 1.10

### ISSUE THREAD

**Issue by jarifibrahim** [MarkusH/django-dynamic-forms#37]
Django 1.10 throws TypeError when trying to use the current middleware.
Middlewares have been changed in Django 1.10 
https://docs.djangoproject.com/en/1.10/topics/http/middleware/#middleware

**Comment by marcosthejew** [comment]
The temporal solution is to write a custom middleware like this:
``
from dynamic_forms.middlewares import FormModelMiddleware
from django.utils.deprecation import MiddlewareMixin

class CustomMiddleware(MiddlewareMixin,FormModelMiddleware):
    pass`

and then adding CustomMiddleware to the middlewares var in settings instead of FormModelMiddleware

**Comment by MarkusH** [comment]
Thanks for the report. I'll try to get a release out ASAP

**Comment by MarkusH** [comment]
[Released to PyPI as 0.5.3](https://pypi.python.org/pypi/django-dynamic-forms/0.5.3)
